version: '3'

services:
  keystone:
    build:
      context: keystone
    depends_on:
      - keystonedb
    container_name: keystone-service
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - DB_USER=keystone
      - USER_PASSWD=password
      - ROOT_PASSWD=secret
    networks:
      custom_network:
        ipv4_address: 192.168.200.2
    ports:
      - "5000:5000"
      - "35357:35357"

  # mind that the database name is hard wired within the playbook.yml, so
  # if it's changed here, it also must be updated in the other file
  keystonedb:
    image: mariadb:10.2
    container_name: keystone-db
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=keystone
      - MYSQL_USER=keystone
      - MYSQL_PASSWORD=password
    volumes:
      - keystone_db:/var/lib/mysql/data
    networks:
      custom_network:
        ipv4_address: 192.168.200.3
    ports:
      - "3306:3306"

  memcache:
    image: memcached
    container_name: keystone-memcache
    networks:
      custom_network:
        ipv4_address: 192.168.200.4
    ports:
      - "11211:11211"

volumes:
  keystone_db:

networks:
  custom_network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.200.0/24"

